### PR TITLE
SQL-1756: Add query file for value transforms

### PR DESCRIPTION
**Pull request by pmeredit**
This generates the following "native query":

```
select `_id`,
    `array`,
    `binary`,
    case
        when `bool0` = 1
        then 0
        else `bool0`
    end as `bool0`,
    `bool1`,
    `bool2`,
    { fn year(`date0`) } as `date0`,
    { fn timestampadd(SQL_TSI_YEAR, { fn timestampdiff(SQL_TSI_YEAR, {ts '2000-01-01 00:00:00'}, `date1`) }, {ts '2000-01-01 00:00:00'}) } as `date1`,
    { fn timestampadd(SQL_TSI_WEEK, { fn timestampdiff(SQL_TSI_WEEK, {ts '2000-01-01 00:00:00'}, `date10`) }, {ts '2000-01-01 00:00:00'}) } as `date10`,
    { fn timestampadd(SQL_TSI_FRAC_SECOND, -1, { fn timestampadd(SQL_TSI_WEEK, { fn timestampdiff(SQL_TSI_WEEK, {ts '2000-01-01 00:00:00'}, `date11`) } + 1, {ts '2000-01-01 00:00:00'}) }) } as `date11`,
    { fn dayofmonth(`date12`) } as `date12`,
    { fn dayofweek(`date13`) } as `date13`,
    { fn timestampadd(SQL_TSI_DAY, { fn timestampdiff(SQL_TSI_DAY, {ts '2000-01-01 00:00:00'}, `date14`) }, {ts '2000-01-01 00:00:00'}) } as `date14`,
    { fn timestampadd(SQL_TSI_FRAC_SECOND, -1, { fn timestampadd(SQL_TSI_DAY, { fn timestampdiff(SQL_TSI_DAY, {ts '2000-01-01 00:00:00'}, `date15`) } + 1, {ts '2000-01-01 00:00:00'}) }) } as `date15`,
    { fn timestampadd(SQL_TSI_FRAC_SECOND, -1, { fn timestampadd(SQL_TSI_DAY, { fn timestampdiff(SQL_TSI_DAY, {ts '2000-01-01 00:00:00'}, `date16`) } + 1, {ts '2000-01-01 00:00:00'}) }) } as `date16`,
    { fn hour(`date17`) } as `date17`,
    { fn timestampadd(SQL_TSI_HOUR, { fn timestampdiff(SQL_TSI_HOUR, {ts '2000-01-01 00:00:00'}, `date18`) }, {ts '2000-01-01 00:00:00'}) } as `date18`,
    { fn timestampadd(SQL_TSI_FRAC_SECOND, -1, { fn timestampadd(SQL_TSI_HOUR, { fn timestampdiff(SQL_TSI_HOUR, {ts '2000-01-01 00:00:00'}, `date19`) } + 1, {ts '2000-01-01 00:00:00'}) }) } as `date19`,
    { fn timestampadd(SQL_TSI_FRAC_SECOND, -1, { fn timestampadd(SQL_TSI_YEAR, { fn timestampdiff(SQL_TSI_YEAR, {ts '2000-01-01 00:00:00'}, `date2`) } + 1, {ts '2000-01-01 00:00:00'}) }) } as `date2`,
    { fn minute(`date20`) } as `date20`,
    cast({ fn timestampdiff(SQL_TSI_FRAC_SECOND, { fn timestampadd(SQL_TSI_MINUTE, { fn timestampdiff(SQL_TSI_MINUTE, {ts '2000-01-01 00:00:00'}, `date21`) }, {ts '2000-01-01 00:00:00'}) }, `date21`) } as double) / 1.000000000000000E+003 as `date21`,
    case
        when `date22` = {ts '2013-09-15 00:00:00'}
        then {ts '2012-08-12 23:00:00'}
        else `date22`
    end as `date22`,
    `date3`,
    { fn timestampadd(SQL_TSI_QUARTER, { fn timestampdiff(SQL_TSI_QUARTER, {ts '2000-01-01 00:00:00'}, `date4`) }, {ts '2000-01-01 00:00:00'}) } as `date4`,
    { fn timestampadd(SQL_TSI_FRAC_SECOND, -1, { fn timestampadd(SQL_TSI_QUARTER, { fn timestampdiff(SQL_TSI_QUARTER, {ts '2000-01-01 00:00:00'}, `date5`) } + 1, {ts '2000-01-01 00:00:00'}) }) } as `date5`,
    { fn month(`date6`) } as `date6`,
    { fn timestampadd(SQL_TSI_MONTH, { fn timestampdiff(SQL_TSI_MONTH, {ts '2000-01-01 00:00:00'}, `date7`) }, {ts '2000-01-01 00:00:00'}) } as `date7`,
    { fn timestampadd(SQL_TSI_FRAC_SECOND, -1, { fn timestampadd(SQL_TSI_MONTH, { fn timestampdiff(SQL_TSI_MONTH, {ts '2000-01-01 00:00:00'}, `date8`) } + 1, {ts '2000-01-01 00:00:00'}) }) } as `date8`,
    { fn week(`date9`) } as `date9`,
    `dbPointer`,
    `decimal128`,
    `int0`,
    `int1`,
    `int2`,
    `int3`,
    `javascript`,
    `javascriptWithScope`,
    `maxKey`,
    `minKey`,
    `null`,
    { fn round(`num0` * { fn power(1.000000000000000E+001, 5) }, 0) } / { fn power(1.000000000000000E+001, 5) } as `num0`,
    { fn ceiling(`num1`) } as `num1`,
    { fn abs(`num2`) } as `num2`,
    { fn log10(`num3`) } as `num3`,
    { fn power(`num4`, 15) } as `num4`,
    { fn power(`num5`, 2) } as `num5`,
    { fn power(`num6`, 3) } as `num6`,
    { fn sqrt(`num7`) } as `num7`,
    case
        when `num8` = 1.700000000000000E-027
        then 4.250000000000000E+001
        else `num8`
    end as `num8`,
    `object`,
    `objectId`,
    `regex`,
    { fn lcase(`str0`) } as `str0`,
    { fn ucase(`str1`) } as `str1`,
    { fn length(`str2`) } as `str2`,
    { fn replace(`str3`, '4', 'hello') } as `str3`,
    `str4`,
    `symbol`,
    `timestamp`
from `reports`.`transforms`
```

### CODE REVIEW

**Comment by jchemburkar** [comment]
@pmeredit this stands for this and the [other tables ops pr](https://github.com/mongodb/mongo-powerbi-connector/pull/43), but what is the way to run these? eg can you just right click -> evaluate pq file, or is there some other way. May be a good candidate to add to testing.md since it seems a little different than the current native query instructions of pasting the sql into the get_data prompt

**Review by bucaojit — APPROVED** [review]
LGTM, nice work!

**Comment by pmeredit** [comment]
> @pmeredit this goes for this and the [other tables ops pr](https://github.com/mongodb/mongo-powerbi-connector/pull/43), but what is the way to run these? eg can you just right click -> evaluate pq file, or is there some other way. May be a good candidate to add to testing.md since it seems a little different than the current native query instructions of pasting the sql into the get_data prompt

@jchemburkar I'll be adding instructions to the testing.md file, but in short:
* Open PowerBI
* Go to "Get Data"
* Select Mongodb
* Connect to localhost, db = reports (though it doesn't matter too much)
* Checkbox reports.transforms and reports.table_ops
* Wait an inordinate amount of time for the Transform box to come up
* Select reports.transforms
* Select "Advanced Query Editor"
* Paste that query in and select Done

Once the SDK and PowerBI are actually using the same code base, we'll be able to run the query files straight through the SDK from the command line with --failOnDirectQueryFailure (or something like that, it's in the --help for PQTest.exe). But we can't use this method now since PowerBI is using a MashupEngine ahead of the SDK :(

**Review by jchemburkar — APPROVED** [review]
lgtm! thanks for the clarification

**Pull request merged**
